# Generated by Django 5.0.4 on 2024-04-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='application',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='email',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_ru',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='link_ru',
        ),
    ]
