# Generated by Django 5.0.4 on 2024-04-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='preload_logo')),
                ('image', models.ImageField(upload_to='preload/', verbose_name='Изображение')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='link_ru',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.FileField(upload_to='social_icons', verbose_name='Иконка'),
        ),
    ]
