# Generated by Django 5.0.4 on 2024-04-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_sub_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Страница "Контакты"', 'verbose_name_plural': 'Страница "Контакты"'},
        ),
    ]
