# Generated by Django 5.0.4 on 2024-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_address_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='email',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='link_en',
        ),
        migrations.AddField(
            model_name='contact',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
    ]
