# Generated by Django 5.0.4 on 2024-04-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_pop_icon_contact_pop_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preload',
            name='logo',
            field=models.FileField(upload_to='preload_logo/'),
        ),
    ]
