# Generated by Django 5.0.4 on 2024-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_application_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Почта', 'verbose_name_plural': 'Почты'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pop_icon',
            field=models.FileField(blank=True, null=True, upload_to='pip_icon', verbose_name='Иконка всплывающего сообщения'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pop_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Всплывающие сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pop_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок всплывающего сообщения'),
        ),
        migrations.AlterField(
            model_name='preload',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
    ]
