# Generated by Django 5.0.4 on 2024-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_address_options_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images', verbose_name='Мета-изображение'),
        ),
        migrations.AlterField(
            model_name='preload',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images', verbose_name='Мета-изображение'),
        ),
    ]
