# Generated by Django 5.0.4 on 2024-04-11 10:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страница "Услуги"',
                'verbose_name_plural': 'Страница "Услуги"',
            },
        ),
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.contentblock')),
                ('sub_title', models.CharField(max_length=150, verbose_name='Подзаголовок')),
                ('sub_sub_title', models.CharField(max_length=150, verbose_name='Под-подзаголовок')),
                ('bonus', models.CharField(max_length=150, verbose_name='Бонус')),
            ],
            options={
                'verbose_name': 'О сервисе',
            },
            bases=('services.contentblock',),
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.contentblock')),
                ('first_field', models.CharField(max_length=150, verbose_name='Первое поле')),
                ('second_field', models.CharField(max_length=150, verbose_name='Второе поле')),
                ('third_field', models.CharField(max_length=150, verbose_name='Треье поле')),
                ('result_field', models.CharField(max_length=150, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Диаграмма',
                'verbose_name_plural': 'Диаграммы',
            },
            bases=('services.contentblock',),
        ),
        migrations.CreateModel(
            name='IconsBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.contentblock')),
            ],
            options={
                'verbose_name': 'Блок с иконками',
                'verbose_name_plural': 'Блоки с иконками',
            },
            bases=('services.contentblock',),
        ),
        migrations.CreateModel(
            name='ImagesBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.contentblock')),
            ],
            options={
                'verbose_name': 'Блок с картинками',
                'verbose_name_plural': 'Блок с картинками',
            },
            bases=('services.contentblock',),
        ),
        migrations.CreateModel(
            name='SliderBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.contentblock')),
                ('duration', models.CharField(choices=[(1, 'right'), (2, 'left')], max_length=100)),
            ],
            options={
                'verbose_name': 'Блок со слайдером',
                'verbose_name_plural': 'Блоки со слайдером',
            },
            bases=('services.contentblock',),
        ),
        migrations.CreateModel(
            name='StepBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.contentblock')),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Блок со слайдером',
                'verbose_name_plural': 'Блоки со слайдером',
            },
            bases=('services.contentblock',),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='services.servicepage', verbose_name='Страница'),
        ),
        migrations.CreateModel(
            name='AboutServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_services/', verbose_name='Изображение')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.aboutservice')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='icon/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='services.iconsblock')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.imagesblock')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide/', verbose_name='Изображение')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='services.sliderblock')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='step/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='services.stepblock')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
