# Generated by Django 5.0.4 on 2024-04-15 06:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutservice',
            name='bonus_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Бонус'),
        ),
        migrations.AddField(
            model_name='aboutservice',
            name='sub_sub_title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Под-подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutservice',
            name='sub_title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='first_field_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Первое поле'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='result_field_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='second_field_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Второе поле'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='third_field_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Треье поле'),
        ),
        migrations.AddField(
            model_name='icon',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='icon',
            name='title_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='step',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='step',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='stepblock',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
    ]
