# Generated by Django 5.0.4 on 2024-04-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutservice',
            name='bonus_ru',
        ),
        migrations.RemoveField(
            model_name='aboutservice',
            name='sub_sub_title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutservice',
            name='sub_title_ru',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='first_field_ru',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='result_field_ru',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='second_field_ru',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='third_field_ru',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='sub_title_ru',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='step',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='step',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='stepblock',
            name='sub_title_ru',
        ),
    ]
