# Generated by Django 5.0.4 on 2024-04-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.contentblock')),
                ('first_field', models.CharField(max_length=150, verbose_name='Первое поле')),
                ('second_field', models.CharField(max_length=150, verbose_name='Второе поле')),
                ('third_field', models.CharField(max_length=150, verbose_name='Треье поле')),
                ('result_field', models.CharField(max_length=150, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Диаграмма',
                'verbose_name_plural': 'Диаграммы',
            },
            bases=('services.contentblock',),
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='bonus',
            field=models.CharField(max_length=150, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='sub_sub_title',
            field=models.CharField(max_length=150, verbose_name='Под-подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='sub_title',
            field=models.CharField(max_length=150, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutserviceimage',
            name='image',
            field=models.ImageField(upload_to='about_services/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(upload_to='icon/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='sub_title',
            field=models.CharField(max_length=50, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slide/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(upload_to='step/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='stepblock',
            name='sub_title',
            field=models.CharField(max_length=150, verbose_name='Подзаголовок'),
        ),
    ]
