# Generated by Django 5.0.4 on 2024-04-11 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_diagram_alter_aboutservice_bonus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutservice',
            options={'verbose_name': 'О сервисе'},
        ),
        migrations.AlterModelOptions(
            name='imagesblock',
            options={'verbose_name': 'Блок с картинками', 'verbose_name_plural': 'Блок с картинками'},
        ),
        migrations.AddField(
            model_name='sliderblock',
            name='duration',
            field=models.CharField(choices=[(1, 'right'), (2, 'left')], default=datetime.datetime(2024, 4, 11, 10, 14, 57, 500771, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icon',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='step/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='stepblock',
            name='sub_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
    ]
