# Generated by Django 5.0.4 on 2024-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_aboutservice_bonus_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
    ]
