# Generated by Django 5.0.4 on 2024-04-12 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_aboutservice_options_alter_imagesblock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='name',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title',
            field=models.CharField(default=datetime.datetime(2024, 4, 12, 8, 46, 51, 716641, tzinfo=datetime.timezone.utc), max_length=150, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
