# Generated by Django 5.0.4 on 2024-04-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.FileField(upload_to='icon/', verbose_name='Изображение'),
        ),
    ]
