# Generated by Django 5.0.4 on 2024-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_icon_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AlterModelOptions(
            name='stepblock',
            options={'verbose_name': 'Блоки с этапами', 'verbose_name_plural': 'Блоки с этапами'},
        ),
        migrations.AddField(
            model_name='service',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок'),
        ),
    ]
