# Generated by Django 5.0.4 on 2024-04-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_step_options_alter_stepblock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutservice',
            name='sub_sub_title',
        ),
        migrations.RemoveField(
            model_name='aboutservice',
            name='sub_sub_title_en',
        ),
        migrations.RemoveField(
            model_name='aboutservice',
            name='sub_sub_title_ru',
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='bonus',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='bonus_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='bonus_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='sub_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
    ]
