# Generated by Django 5.0.4 on 2024-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_options_alter_servicepage_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images', verbose_name='Мета-изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слоган[en]'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images', verbose_name='Мета-изображение'),
        ),
        migrations.AlterField(
            model_name='sliderblock',
            name='duration',
            field=models.CharField(blank=True, choices=[('right', 'справа'), ('left', 'слева')], max_length=20, null=True),
        ),
    ]
