# Generated by Django 5.0.4 on 2024-06-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_service_keywords_alter_service_meta_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderblock',
            name='duration',
            field=models.CharField(blank=True, choices=[('справа', 'справа'), ('слева', 'слева')], max_length=20, null=True),
        ),
    ]
