# Generated by Django 5.0.4 on 2024-04-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='sub_title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='sub_title_ru',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='title_ru',
        ),
    ]
