# Generated by Django 5.0.4 on 2024-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconsblock',
            name='type',
            field=models.CharField(default='icons', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='imagesblock',
            name='type',
            field=models.CharField(default='images', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='sliderblock',
            name='type',
            field=models.CharField(default='slider', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='sliderblock',
            name='duration',
            field=models.CharField(choices=[(1, 'right'), (2, 'left')], max_length=100, verbose_name='Направление'),
        ),
    ]
