# Generated by Django 5.0.4 on 2024-04-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(verbose_name='Мета-описание')),
                ('meta_image', models.FileField(default='static/icons/LOGO.svg', upload_to='meta_images')),
            ],
        ),
    ]
