# Generated by Django 5.0.4 on 2024-04-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='sub_title',
            field=models.CharField(max_length=200, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='about_page'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='about_us.sliderblock'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='about_slide'),
        ),
    ]
