# Generated by Django 5.0.4 on 2024-04-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesblock',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sliderblock',
            name='title',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
