# Generated by Django 5.0.4 on 2024-04-09 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_remove_imagesblock_title_remove_sliderblock_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about_us.contentblock')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('about_us.contentblock',),
        ),
        migrations.RemoveField(
            model_name='imagesblock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sliderblock',
            name='description',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='about_us.iconsblock')),
            ],
        ),
    ]
