# Generated by Django 5.0.4 on 2024-04-11 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_aboutpage_sub_title_alter_icon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderblock',
            name='duration',
            field=models.CharField(choices=[(1, 'right'), (2, 'left')], default=datetime.datetime(2024, 4, 11, 10, 14, 47, 157805, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
