# Generated by Django 5.0.4 on 2024-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaData',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок'),
        ),
    ]
