# Generated by Django 5.0.4 on 2024-04-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_delete_metadata_aboutpage_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('meta_image', models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images')),
                ('technical_works', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Информация о сайте',
                'verbose_name_plural': 'Информация о сайте',
            },
        ),
    ]
