# Generated by Django 5.0.4 on 2024-04-09 05:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_iconsblock_remove_imagesblock_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'О Нас', 'verbose_name_plural': 'О Нас'},
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['order'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': 'Иконка', 'verbose_name_plural': 'Иконки'},
        ),
        migrations.AlterModelOptions(
            name='iconsblock',
            options={'verbose_name': 'Блок с иконками', 'verbose_name_plural': 'Блоки с иконками'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='imagesblock',
            options={'verbose_name': 'Блок с картинками', 'verbose_name_plural': 'Блоки с картинками'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterModelOptions(
            name='sliderblock',
            options={'verbose_name': 'Блок со слайдером', 'verbose_name_plural': 'Блоки со слайдером'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='sub_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='about_us.aboutpage', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
