# Generated by Django 5.0.4 on 2024-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='site_password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
