# Generated by Django 5.0.4 on 2024-04-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_alter_aboutpage_options_alter_contentblock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Страница "О Нас"', 'verbose_name_plural': 'Страница "О Нас"'},
        ),
    ]
