# Generated by Django 5.0.4 on 2024-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='URL видео'),
        ),
    ]
