# Generated by Django 5.0.4 on 2024-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_alter_contentblock_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='about_page', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='about_slide', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='sliderblock',
            name='duration',
            field=models.CharField(blank=True, choices=[('right', 'right'), ('left', 'left')], max_length=20, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='sliderblock',
            name='uppercase',
            field=models.BooleanField(default=False, verbose_name='Верхний регистр'),
        ),
    ]
