# Generated by Django 5.0.4 on 2024-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_alter_aboutpage_keywords_alter_icon_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images', verbose_name='Мета-изображение'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='meta_image',
            field=models.FileField(blank=True, default='static/icons/LOGO.svg', null=True, upload_to='meta_images', verbose_name='Мета-изображение'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_password',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='technical_works',
            field=models.BooleanField(default=False, verbose_name='Тех обслуживание'),
        ),
    ]
