# Generated by Django 5.0.4 on 2024-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0009_alter_aboutpage_meta_image_alter_siteinfo_meta_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderblock',
            name='duration',
            field=models.CharField(blank=True, choices=[('right', 'справа'), ('left', 'слева')], max_length=20, null=True, verbose_name='Направление'),
        ),
    ]
