# Generated by Django 5.0.4 on 2024-04-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioduration',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Загловок'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='location_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
