# Generated by Django 5.0.4 on 2024-04-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioduration',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='sub_title_ru',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='location_ru',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='title_ru',
        ),
    ]
