# Generated by Django 5.0.4 on 2024-04-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioduration_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
