# Generated by Django 5.0.4 on 2024-04-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfoliopage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='content',
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
    ]
