# Generated by Django 5.0.4 on 2024-06-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfoliopage_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioduration',
            options={'verbose_name': 'Направление проекта', 'verbose_name_plural': 'Направление проектов'},
        ),
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'verbose_name': 'Изображения портфолио', 'verbose_name_plural': 'Изображении портфолио'},
        ),
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'verbose_name': 'Портфолио проекта', 'verbose_name_plural': 'Портфолио проектов'},
        ),
        migrations.AlterField(
            model_name='portfolioduration',
            name='image',
            field=models.ImageField(upload_to='portfolio_duration/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='portfolioduration',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='portfolio.portfoliopage', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to='portfolio_projects/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.portfolioduration', verbose_name='Направление'),
        ),
    ]
