# Generated by Django 5.0.4 on 2024-04-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfoliopage_content_portfoliopage_sub_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'verbose_name': 'Страница "Портфолио"', 'verbose_name_plural': 'Страница "Портфолио"'},
        ),
    ]
