# Generated by Django 5.0.4 on 2024-09-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfoliopage_meta_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'ordering': ['order'], 'verbose_name': 'Портфолио проекта', 'verbose_name_plural': 'Портфолио проектов'},
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок'),
        ),
    ]
